---
title: "HepG2 ENCODE analysis"
author: "David Corujo"
date: "2023-09-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load packages

```{r}
library(rtracklayer)
library(GenomicRanges)
library(regioneReloaded)
```


# Load data for selected facors

## Load metadata

```{r}
metadata <- read.delim("./encode_metadata.tsv", skip = 1)
nrow(metadata)
```

## Load bed files and annotate with target name

```{r}
files <- list.files("./ENCODE", full.names = F)
anno <- data.frame(fileName = files,
                   fileID = gsub(".bed.gz", "", files))
anno$target <- unlist(lapply(anno$fileID, FUN = function(x) metadata$Target.of.assay[grep(x, metadata$Files)]))
anno$lab <- unlist(lapply(anno$fileID, FUN = function(x) metadata$Lab[grep(x, metadata$Files)]))
View(anno)

extraCols_narrowPeak <- c(singnalValue = "numeric", pValue = "numeric",
                          qValue = "numeric", peak = "integer")
rsList <- lapply(anno$fileName, FUN = function(x) rtracklayer::import(paste0("./ENCODE/", x), extraCols = extraCols_narrowPeak))
names(rsList) <- paste(anno$target, anno$fileID, sep ="_") 
rsList
```

# Export region sets as RDS

```{r}
saveRDS(rsList, file = "regionSets/ENCODE_sets.RDS")
```

# Load region sets as RDS

```{r}
rsList <- readRDS("regionSets/ENCODE_sets.RDS")
```

# Test permTest

```{r}
permRes <- crosswisePermTest(Alist = rsList,
                              genome = "hg38",
                              evFUN = "numOverlaps",
                              ranFUN = "resampleGenome",
                              count.once = TRUE,
                              ntimes = 10,
                              mc.cores = 20)
```

# Check results from local run

```{r}
permRes <- makeCrosswiseMatrix(permRes)
plotCrosswiseMatrix(permRes)
```

# Check results from HPC run

```{r}
permRes <- readRDS("hpcResults/permResENCODE.RDS")

# Check all results
permRes <- makeCrosswiseMatrix(permRes, zs.type = "z_score", pvcut = 0.01, subEX = 0)
plotCrosswiseMatrix(permRes)

# Some selection of factors that could give a nice illustrative example
seltf <- c("CTCF", "RAD21", 
           "MAFK_ENCFF458PBB", "MAFF", 
           "POLR2A_", "POLR2G", 
           "JUN_ENCFF079UOJ", "JUND_ENCFF562YSV",
           "FOXA1_ENCFF081USG", "FOXA2_ENCFF759YCY")
seltf2 <- c("POLR2A_", "FOXA1_ENCFF081USG", "FOXA2_ENCFF759YCY", "EZH2")
selhist <- c("H3K27me3", "H3K4me3", "H3K27ac", "H3K4me2")

# Symmetrical matrix with TFs
permRes <- makeCrosswiseMatrix(permRes, zs.type = "z_score", pvcut = 0.01, subEX = 0, selectCol = seltf, selectRow = seltf)
plotCrosswiseMatrix(permRes, matrix_type = "association")

# Asymmetrical matrix with TF vs histones

permRes <- makeCrosswiseMatrix(permRes, zs.type = "z_score", pvcut = 0.01, subEX = 0, selectCol = seltf2, selectRow = selhist, symm_matrix = F)
plotCrosswiseMatrix(permRes, matrix_type = "association")
```

# Association results from Roberto

## Load
```{r}
permRes <- readRDS("10_vs_all.rds")
```

## Make matrix

```{r}
permRes <- makeCrosswiseMatrix(permRes, symm_matrix = F, hc.method = "average")
```

## Plot

```{r}
plotCrosswiseMatrix(permRes)
```

# Multilocal z-score
```{r}
encode_filtered <- readRDS("regionSets/ENCODE_filtered.RDS")
encode_universe <- readRDS("regionSets/universe_ENCODE_filtered.RDS")
```

```{r}
mlz <- multiLocalZscore(encode_filtered$POLR2A_ENCFF159PYD,
                        encode_filtered, 
                        ranFUN = "resampleRegions", 
                        ntimes = 100,
                        genome = "hg38", 
                        universe = encode_universe,
                        window = 2000,
                        step = 50)
```

```{r}
mlz <- makeLZMatrix(mlz, normalize = T)
plotLocalZScoreMatrix(mlz, maxVal = 1) +
  theme_bw()
```

```{r}
plotSingleLZ(mlz, RS = c("POLR2G_ENCFF551IJP", "H3K4me3_ENCFF982DUT"))
```

