---
title: "Untitled"
author: "David Corujo"
date: "2023-10-03"
output: html_document
editor_options:
  chunk_output_type: console
---

# Load packages

# Check results from HPC run

# Generate matrix and plot for all tests

```{r}
nzPermList_zs <- lapply(nzPermList, FUN = makeCrosswiseMatrix, symm_matrix = F, zs.type = "z_score")
lapply(nzPermList_zs, FUN = plotCrosswiseMatrix)

test1 <- nzPermList[[2]]
test1 <- makeCrosswiseMatrix(test1, symm_matrix = F)
plotCrosswiseMatrix(test1, ord_mat = list(1:35,1:10))
plotCrosswiseMatrix(test1)
```

# Plot nzs and zscore

```{r}
# Generate a table for plotting
dt_test<-data.frame(frac=paste0("V",1:10),zs=matX[,nameX],nzs=matXn[,nameX],nreg=vecLength)
dt_test

p1<-ggplot(data=dt_test,aes(x=nreg,y = zs),) +
  geom_line( color="red")+
  geom_point(color="red") + ggtitle(paste0("CREB1_ENCFF314KET vs ",nameX) )+
  xlab("num. of regions") + ylab("z-score") + theme(plot.title = element_text(size=8))

p2<-ggplot(data=dt_test,aes(x=nreg,y = nzs),) +
  geom_line( color="green")+
  geom_point(color="green") + ggtitle(paste0("CREB1_ENCFF314KET vs ",nameX) )+
  xlab("num. of regions") + ylab("norm z-score") +  theme(plot.title = element_text(size=8)) + ylim(0,20)

p1|p2 # plot results
```

