---
title: "ReMap K-562"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Setup

```{r}
library(GenomicRanges)
library(rtracklayer)
library(regioneReloaded)
```

# Load ReMap data for K-562

```{r}
remap_k562 <- rtracklayer::import("/mnt/data1/ReMap/remap2022_K-562_nr_macs2_hg38_v1_0.bed.gz")

# Remove non-standard chromosome annotations
seqlevels(remap_k562)
remap_k562 <- keepStandardChromosomes(remap_k562, pruning.mode = "tidy")
seqlevels(remap_k562)

# Include a new column with the binding factor name ONLY
factor_names <- sapply(remap_k562$name, FUN = function(x) unlist(strsplit(x, ":"))[1])
remap_k562$factor <- factor_names
remap_k562

# Split into one GRanges per factor
remap_k562_list <- split(remap_k562, ~factor)
remap_k562_list <- GRangesList(remap_k562_list)
names(remap_k562_list)
length(remap_k562_list)

# Save Granges list of remap peaks and original granges
dir.create("regionSets", showWarnings = FALSE)
save(remap_k562_list, file = "regionSets/remap_k562_list.RData")
```

# Load GRanges list object

```{r}
load("regionSets/remap_k562_list.RData")
```


# Subset a few factors of interest 

```{r}
sel <- c("CTCF", "RAD21",
         "JUN", "JUNB", "JUND",
         "MAFF", "MAFG", "MAFK",
         "KDM1A", "HDAC2",
         "CEBPB", "CEBPD", "CEBPG",
         "CREB1", "CREBBP")

all(sel %in% names(remap_k562_list))

tf_sel <- remap_k562_list[sel]
tf_sel
```

# Save subset of factors

```{r}
save(tf_sel, file = "regionSets/tf_sel.RData")
```


# Run permTest

```{r}
perm_res <- crosswisePermTest(Alist = tf_sel,
                              genome = "hg38",
                              evFUN = "numOverlaps",
                              ranFUN = "resampleGenome",
                              count.once = TRUE,
                              ntimes = 100,
                              mc.cores = 20) 
```

# Visualize results

```{r}
perm_res <- makeCrosswiseMatrix(perm_res)
plotCrosswiseMatrix(perm_res, lineColor = "black", matrix_type = "correlation")
```

# Retrieve results rom minastirith

```{r}
load("/Users/dcorujo/minastirith_mount/REGIONER/hpcResults/remap_perm.RData")
perm_res <- makeCrosswiseMatrix(perm_res, pvcut = 0.01, subEX = 0, zs.type = "z_score")

plotCrosswiseMatrix(perm_res, matrix_type = "association")
```

